### ISSUE TITLE
Tickbox Convert Object Results to String does not JSON.Stringify 

### ISSUE THREAD

**Issue by Yawiss** [mbaersch/extract-json#1]
As detailed in MeasureSlack here:

https://measure.slack.com/archives/C2PNCCZ1V/p1716556452947859 

On line 86 here: https://github.com/mbaersch/extract-json/blob/main/template.tpl it does a typeof check and only if it's a string, it turns res into a JSON Stringified string. But it was a string already. 

It should check it's an object, and if conversion is requested, then stringify it.

**Comment by mbaersch** [comment]
the web variable did not include this error - no idea how that happened. Wil be resolved with the recent update
